

/*** Document Load Test ***/
$(document).ready(function() {
  console.log("document loaded");
  window.n = 0
});

/***  Nav Bar Desktop to Mobile view Responsiveness ***/
function MobiileNavOpen() {
  var x = document.getElementById("mynavbar");
  if (x.className === "navbar") {
    x.className += " responsive";
  } else {
    x.className = "navbar";
  }
}

/*** Audio Files Dynamic Switch ***/

var playing = false;

function action() {
  var audio = document.getElementById(`audio-0${n}`);
  if (playing === false) {
    audio.play();
    playing = true;
  } else {
    audio.pause();
    playing = false;
  }
}

// var playing = true;

// function pause() {
//   var audio = document.getElementById(`audio-0${n}`);
//   if (playing === true) {
//     audio.pause();
//     playing = false;
//   // } else {
//   //   audio.pause();
//   //   playing = false;
//   }
// }

/*** UX Functions separated by viewport sizes ***/
const isDesktop = window.matchMedia("only screen and (min-width:641px)").matches;
const isMobile = window.matchMedia("only screen and (min-device-width: 320px) and (max-device-width: 480px)").matches;

$(window).on("load", function() {
  console.log("window loaded");

  // var opening_animation = false
  // if (
  //   isDesktop
  //   && opening_animation
  // )


  {

    $( "#all-content" ).delay( 6000 ).animate({ "marginTop":"-35px" }, 2000 );
    $( "#top-part" ).delay( 6000 ).animate({ height: "15%" }, 2000 );
    $( "#first-opening-p" ).delay( 7000 ).animate({ height: "100%" }, 3000 );
    $( "#opening-title" ).delay( 7500 ).animate({ "marginTop":"100px" }, 3000 );
    $( "#opening-title" ).delay( 8000 ).fadeOut( 3000 );
    $( "#bottom-part" ).delay( 0 ).animate({ height: "25%" }, 3000 );
    $( "#opening-poem" ).delay( 2000 ).animate({ "opacity":"1" }, 3000 );
    $( "#opening-poem" ).delay( 8500 ).fadeIn( 2000 );
    $( "#first-opening-p" ).delay( 9000 ).toggleClass('scroll', 3000 );

  }

  if (isMobile) {}

});

/*** All Brick Link Trigger Actions (Reveal Content) ***/

// Wait for the page to load first
$(window).on("load", function() {

  //Get a reference to the link on the page

  $('[id^="brick"]').on('click', function() {

    $('.transcript-container').text('')

    if (isDesktop) {

      var target = parseInt(this.id.slice(-1))
      if (target == n + 1 || n == 5 && target == 1) {
        if (n == '0') {
          window.n = target
          $("#first-opening-p").delay(2000).animate({height: "1.5vh"}, 3000);
          $("#all-content").delay(2500).animate({"marginTop": "10px"}, 3000);
          $("#all-content").delay(2500).animate({height: "93%"}, 3000);
          $("#title-top-01").delay(2500).addClass("remove", 3000);
          $("#top-part").delay(2500).animate({height: "78%"}, 3000);
          $("#bottom-part").delay(2500).animate({height: "10%"}, 3000);
          $("#main-opacity").delay(1000).addClass("full-opacity", 3000);
          $("#main-opacity").delay(1000).animate({height: "8%"}, 3000);
          $("#first-opening-p").delay(6000).toggleClass('scroll', 3000);
          $("#experience").delay(3000).animate({height: "88%"}, 3000);
          $("#all-isolated-title").delay(3000).animate({height: "10%"}, 3000);
          $("#second-brick").delay(3000).animate({width: "0vw"}, 3000);
          $("#second-brick").delay(0).fadeOut(3000);
          $("#first-brick").delay(3000).animate({width: "101vw"}, 3000);
          $("#fourth-brick").delay(1000).addClass("bg-change", 3000);
          $("#first-brick").delay(3000).addClass("experience-bg", 3000);
        }

        else {
          window.n = target
          $('[id^="isolated"]').fadeOut(2000);
          $(`[id^="isolated"][n=${n}]`).delay(1000).fadeIn(2000);
          $(`[id^="isolated"]:not([n=${n}])`).delay(1000).animate({height: "0%"}, 2000);
          $('.experience-poem').fadeOut(2000);
          $(`#ex-0${n}`).delay(1500).fadeIn(2000);
        }
      }

    }
    else if (isMobile) {}
    return false

  })

  //////////////////
  console.clear()

  /// Scrolling text ///

  var messages = {
    1: {
      0: 'Narrator: Carlos Truan Test',
      25: 'I could go straight to work. And I was in a, it was called a—a re-entry program. That was in Dallas and it was geared towards repeat drug offenders. Felon, you know, felony, drug offenders. And so I was there with a bunch of other people in that group, and I was the only one that tattooed and it wasnt-I was the only person that tattooed there.',
      100: 'What did that—what did that feel like for you as a young person? To do what? To do dope, to get involved like that? [pause] I dont know that—there, there was just something that drew me to it. I wasnt like—and my friends that I hung out with, they didnt—it, it was a secret, you know, I didnt tell anybody. It was kind of my own little thing and these guys...I mean, I dont wanna say that I felt safe with them. I wasnt like, oh, these guys are gonna take care of me. I mean they did—you know, actually kind of a weird thing. I, the very first time I did it, I ODed. I went out and they were freaked out and they were so pissed at me. They were like your dads gonna kill us if he finds out. I came to. And they had me in the backyard of this other dudes house. And he was spraying me with a water hose. I was completely out of it. They brought me back, I guess, I mean, I didnt die, but you know—I went out, y—and they had to revive me or whatever. And they said they would never give it to me ever again and I was like, what, why?',
      170: 'They had already given me chances, you know? I had already been to rehab once, i had already gone to jail like two times for coming up dirty. And I knew this time, there was no more chances. So I dipped out the back and hauled ass, got in my truck and took off. And then they started coming, looking for me at my house. My buddy came to town from Los Angeles...And I told him everything, you know, I was like, look, Im strung out. Im on the run. I just gotta kind of get my shit together, you know? And he was like, what do you need? Hes like my wifes a doctor. Tell me what meds you need or whatever. And well put you up. Ill buy you a plane ticket here. It was crazy. Ill buy you a plane ticket. You can stay at my house. Dude had kids and stuff. You know, he was a gangster, you know, but he was still like, i mean, he was good. He was good to me. And he brought me out there and let me kick at his house. His wife got me some meds or whatever, some detox meds and uh...yeah. And I tattooed out there. But I couldnt stay sober.',
      305: 'I got really involved in the program in [prison], you know what I mean? I started going to meetings in there and, I think I decided at one point, you know—I was in the county jail in Dallas, which is a really crazy jail. But <unintelligible 01:19:39> I think its like 10 stories high our something...And those guards did not care. And I was kicking dope in there and, you know, like I literally had vomit on the front of my jumper and i had shit on the back of my jumper cuz it was coming out both ends, you know? I was that guy with the shitty pants in jail. And Im going to prison, and I dont know whats gonna happen at that point. I hadnt been sentenced yet. I had like 13 felonies, you know? And I think at some point I had decided, and I was like man, Im over this, this isnt working. Im gonna try something else.',
      570: 'A Greek letter adopted as a symbol for gay liberation in 1970 by the New York Activists Alliance.',
      800: 'So my PO said, well, what are you gonna do? You know, when I got out and I went to go meet her or whatever. And she was like, what are you gonna do? And I said, well Im a tattoo artist. I got a job at my buddys shop, you know? And she was like, yeah, right. Youre not gonna do that. And I was like, oh, well, why not? I was like, what do you mean? Its like a regular—to me, it was a regualr job. She goes, Im not dumb. Shes like, i know that tattoo shops are nothing but gangsters and prostitutes. I was like, what? Or bikers, bikers and prostitutes. I was kind of like—floored, you know. And I was like shit, Im gonna have to get like a regular job. And I mean, I did. I went and got a baking job. And I had done baking while I was incarcerated. Briefly, you know what I mean? I was like, yeah, made one piece of bread. It was probably $7 an hour or something like that. So when I would go to work [tattooing] on Tuesday and Wednesday, I would make the same amount of money or more than my paycheck in those days, you know? It was wild. But...I mean, I did good at it. I did good at the baking. I took to it, and I dealt with it and I made the best of it. But yeah, it was weird. All my friends that were tattooing, they knew I was—you know, they knew me as a tattooer. They were like, why are you baking? They just didnt get it. Theyre like doing all cool tattoo guy stuff. And I was like, oh man, I gotta be up early. Cuz I gotta be at the bakery at four in the morning.',
      900: 'Like, who is this joker with all these colorful tattoos and everything, you know, friendly tattoos. They used to say hes got friendly. <laughs>',
      970: 'I mean, it did suck because Austin, its—the shop that I was at, wasnt like Dallas, where you just showed up and tattooed, you had to have a clientele, and all my clientele was gone. Cause I had been gone—probably a year and a hald before I got locked up, I was on the streets, you know? Just going, loving from place to place or motels or whatever. And then finally getting sent back and then I was gone for a year and then in Dallas for a year. So its like three and a hald years that my customers were getting tattooed by everybody else, you know? And I wasnt relevant anymore.',
      1410: 'It was tough in Austin. It was really, really hard. It wasnt a bounce back. I mean, other than having to work in the bakery. But as far as tattooing goes, I didnt make any money, you know? i wasnt making any money. It was a different, it was a different thing. You know, tattooings a little bit different, I think because of the whole social media and how it kind of changed things. I think by the time I made it back to Austin, it was 2014. It was very discouraging. Theres so many—everyone was so good and they were tattooing so different and what I was doing wasnt happening anymore, you know?',
      1460: 'No, but I, I love it. I love what happened, you know what I mean? I love that Im here and that I, you know, and I get to do this thing and, that everything happened when it happened, everything happened how it happened and when it happened, because if it had happened any other way, I dont know what it would be like, you know?',
      1480: 'And its like <pause> so sometimes its hard to believe, right. That its like, when I talk about how it was, and where I came from, sometimes I cant believe it, that Im sitting here in my house with my family, with a car that has insurance, the bills are paid, have a beautiful shop, amazing friends. Im able to set boundaries, like I know how to do those things. I know what a relationship is, what I want my relationship to look like. You know what I mean? With all the people around me, you know? And whereas, before I had to learn all that stuff. And I think that its helped all of our experiences,right? Our life experiences play a part as to whats happening today. Theres something that I always say to people <clears throat> not to get too programmy or anything, but its a real life thing, you know? And it can be applied to anybody, whetther you are a alcoholiv or a junkie or a regular person or a normal person. Its like every experience that we have in life <pause> is an opportunity for growth, whether its god or bad, right. If I had a bad relationship, then you take the good out of that. You take the good out of that. And I think that thats one of the most valuable things that Ive learned. To move forward from any situation, whether its good or bad, you know? So. '
    },

    2: {
      25: 'I had written a letter. I still have that letter. You know, I had written another letter to Ms. Major and she sent me a response and ti was a pink envelope on pink stationery. That was like, I got, we, got your letter. We will be there on this date. And they basically came down there and kicked the fuckin door in and were like, We wanna see her and we wanna see everybody thats involved and you need to present them. FP (01:12:47): They brought an attorney and they were like, were doing a, were doing a wellness check for our client. And thats what really started the relationship with - with me and Mayor.',
      65: 'So. I... was in the closet when I was at Folsom, but I had— I would get, um, there were like these queer newsletters and um, that when I first—first connected with Miss Major. And um, at the time the attorney that was running TGI Justice project was— I think his name was Alexander Lee. And they were like in a garage in Oakland, you know, it was like real, real small. And they just had these little trifold pamphlets or whatever and I would get em and wait until everybody went to sleep. And Id be like looking at it uner the light of the TV. And I told myself, you know, once I get to a place where its safer to do so Im gonna come out. Like I had already— I had already planned that, you know, and my, my friend that passed away this year, I had come out to him, you know, and told him like, Hey, you know, this is — this is who I am or whatever.',
      130: 'FP (01:11:15): Im like, oh, you know, this what happened. Im going to the hole with Shy Boy. Well bitch, hold on, let me pack my shit. Ima go too. And so there was this little chain of things and I just like, I had this spark of an idea and I was like, matter of facts, lets just refuse to lock up. Lets all go sit on the bleachers. And when they, when they re-call the yard, nobody say nothing, just put your ID in front of you and tell, tell them were refusing to lock up. Were all going to the hole with Shy Boy, you know, and we did that and we shut the prison down for free days, had multiple standoffs with the police. Like it was a, it was a, it was a whole-ass odreal. Um, they tried to kill me after that. FP (01:18:23): I mean its, uh, its beautiful in a way that I- I have not experience in th air quotes free world. Yeah. Just the- the level of interdependence and mutual aid it amongst peoplein prison, it, it looks, it looks way different. Yeha. It looks way different. And like even- even things like um, like um, like transformative justice, like I didnt even know the fuck that word was until like a year ago, you know? But thats literally what happens. And its like, you— you cant get away. We wake up and I have to look at, at, at your musty ass every day. So I may be upset by something you did. And maybe we dont talk for a while, but, but nobody better try no stupid with you either because youre mine and Im yours. And I, I will, its just— theres a kind of radical unity that happens and people figure it out. FP (01:19:29): They figure out how to work through really tough, you know, cause its not always perfect. People are messy, you know, but you, you cant fuck with none of them girls in there and not get your whole fuckin ass handed to you. Even if they—theyre—they could be mortal fuckin enemies and the kind of radical unity that will show up if some random dude fucks with one of them, girls is just—its, its unparalled. And I—dont, I just not saying it dont exist. I just, I have not seen it at the level that i experienced when i was in prison.  ',
      140: 'FP (01:10:21): And you know, we, uh, we all had a reputation for like, I guess keeping the peace in that way. Cause we would sock you the fuck out if you fucked with anybody that was queer. You know, um, up to and including like— like really life threatening, physical violence, if we needed to, you know?',
      295: 'FP (00:46:05): And I was like, fuck you talking about? Hes like, no like to lower, lower security. And hes like, I put you up for these two places. And a week and a half later I was at a medium security place. So. And thats the place that I came out. And thats where, thats where all of my- I dont know, I felt like Folsom was like, where was the breeding ground for, you know, militancy and social activism and like me being radicalized. It like— all of that information, all of those conversations were there. That community was there. It just looked very different, cause it was very hyper masculine in lots of ways. And then yeah, I got to the next place, which was dormitories and it was like fuckin Camp Snoopy. You know, people still got touched up, but it was just not— nobody was getting stabbed at this place. FP (00:47:01): Ill put it that way. Like if you saw a ight at Folsom, it was because those two people lpoved each other. Like they were friends. Or it was a diversion cuz somebody was getting killed around the corner. So this other place that I went to was not that. It was like all, it was a heads up fade. It was just, it was super like going from that to like just fist fights. I was like, man, this place is super chill. This is great. I can go home from here, you know? And thats the place that I came out at. Mm-hmm <affirmative>',
      430: 'I dont even even know if the Abolitionist is still around, but like I had an article in there... and in the magazine in These Times and yeah, we were— I spent a lot of time in the hole, Tamara. <laughs> Uh, for like direct action shit, cause it was, I wont say that I was necessaryily asked to do it. I was just always willing. I was always willing to give the information to, to Mayors organization, but I was always willing to go to hell too.',
      580: 'FP (00:15:15): Yeah. Um, really the first time i went out on the— on the blade, you know, like if yall dont know what the blade is, its, uh, its the hoe stroll, you know? Um, and I was like, I got directed there by this crust punk in Hollyowood, I was on Hollywood Boulevard and I was like, Im trying to find, you know, other people or whatever. And so she was like, the only place, I know they hang out is like over there, you know, but I dont know if you want to go over there. FP (00:15:43): You know? And Hollywood at that time was a-LA in general was just different—LA in the nineties was...it was wold as fuck. So, um, yeah, it was people, you know, it was like cars turning in and out of this lot and people fuckin in the street and just, you know, it was a, it was a fuckin zoo out there and it was really fucking dangerous too, you know. But yeah, I, I basically,—her name was Antoinette. Um, it was like so i was right on like Hollywood and— Hollywood, um, which at the time was like, that was the spot. Theres a 24 hour donut spot there. And so, you know, youre not technically loitering, you know what I mean? You an suck a dick and then buy a donut and the cops will leave you alone. But, um, yeah, like she basically in a nutshell was just like, you know, the fuck are you doing out here? FP (00:16:38): Like, youre gonna get yourself fucking killed. And she was really irritated with me. Um, cause she had to stop working. And— told me to get on the bus with her. She was gonna take me to the shelter, which doesnt exist any more. But um, shes looking at me, were on the bus cause she had asked me what my name was and I told her my dead name and shes like no, bitch, that dont work. Like <laugh> and uh, she looked—she kept looking at me and she said that— she said Faith. And I was like, what is, what is that? You know? And shes like, thats your name. Thats what we gon call you. Which I dont I dont know if people really talk about that, that like all the— all the girls, I know... somwbody like gave them their name. Like it just got picked up and usually it got picked up in the streets, you know, even in prison its that way. FP (00:17:30): Um, or if you didnt have one and then you like, come out in prison, like somebody comes up with a name for you that ends up sticking, you know? Um but her whole thing was just that she— she really wanted me to be something that wasnt what was going on out there. So thats— thats where that name comes from. Um, she took me to this homeless shelter that was like all people, like elderly queer people with just a sea of fucking green cots you know? Um, in a warehouse, some—somewhere in West Hollywood. And uh, yeah, she stayed awake all night while I had slept and watched— watched me so that nothing would happen to me. But yeah, thats how I got my name. <laugh>',
      660: 'FP (01:08:18): ...I got kicked out of that prison cause I started a riot.',
      681: 'FP (01:14:22): Other things got started there too, where it was, um, the start of the class action suit that was suing the department of corrections and rehabilition for the demand that they pay for trans affirming care. You know, all of it, not just hormones, not six month wait to see Dr. Lori Kohler, one doctor that served the entire trans population in all of the department of corrections. You know, it could be months before you see her. TS (01:15:42): One person in all of the state? FP (01:15:43): You should look her up. Dr. Laurie Kohler. Shes a real one. You know, shes not a part of the, the department of corrections. This is something that she does. She works at UC San Francisco taht started the entire trans healthcare program in California prisons. And yeah, it was all through telehealth through U C SF and she was the only one. You know, so youd put in that thing and like, even, even though their doctors technically should have been able to do it, they— they wouldnt, you know, so, so yeah, but now like, that— that lawsuit won. And so now, like thats a—thats a whole thing. Like they dont have to pay for everything now.'
    },

    3: {
      0: 'Bernie Lieving <Laughs> So there was a— ther was an old school bus on site doing tattoos. So I went and I had— before, I had done some community college. And had ome exhcnage students in a couple of my classes in community college and one of whom was Japaense and I ask her, I remember one time, can you write the characters of "no government" for me? And tell me how to say it. Just, you know, I mean, I had no tie to Asian culuture or Japan or it was just— it was in a political science class. So she wrote the characters out for me and it comes out to, I think its pronounced museji which means no government. So I had soemwhere, in a notebook or in, I dont know how I had those characters with me stuck in a book or something. But so anyway I did, and I got the musehi character tattooed on my forearm. Going down my forearm. In this school bus. Black outline with red coloring inside. Yeah, I dont know how I took care of that tattoo, <laughs> I mean we I dont think we had an opportunity to wash anything for days. So I got this no government in Japanese characters tattooed on my forearm at Stonehenge and again, managed to not have any, you know, infectious, bloodborne issues associated with getting tattooed in back of a bus where, I had no awareness of universal precautions or anything. (25:18:84) Bernie Lieving Oh no, I— and I guess the, then in 981 was the first time that a few of us punks went to Salinas, California and got tattoed. For the first time. (25:37:28): Tamara Santibanez Wow. What was in Salinas? (25:40:87): Bernie Lieving The tattoo shop. So we, you know, probably drove drunk over to Salinas from the Monterey area. And I went to a tattoo shop and I— my first tattoo was a skull and crossbones. With a banner underneath it that said rebel. 35:02.35 Bernie Lieving ...I also, that summer solstice of of 84 Nancy and I camped at Stonehenge. And that was the last time that the English government allowed Stonehenge to be open to the Summer Solstice festival.',
      185: '(34:24:78): Bernie Lieving So Nancy, Nancy, and I went to the England in 84. She ledt, I hung out for six months or so and I got to hang out with Dirt, the band Dirt. I got to hang out with Flux of Pink Indians. I went to Dial House and stayed with Crass for a couple days, and hung out with Steve Ignorant and Gee and um, actually- (34:53:96): Tamara Santibanez Cool. (35:02:35): Bernie Lieving -I joke about this now. But you know I think I fell in love momentarily with Gee becuase I was hanging out with her in her studio and all her collage art and everything and- you know shes probably...Im almost sixty, she must be, Im just guessing, in her- Penny Rimbaud is like close to 80 so I dont know but there was this, like, they were so generous and open and kind and made me food and I got to stay there and listened to the early recordings of the early manifestations of Acts of Love, which was that record that- that sort of got orchestral and very, a little bit different than the old Crass stuff, and Steve Ignorant was so kind.  ',
      240: '(36:14:61): Bernie Lieving And on the way to Salisbury on the train from Lodon we emt the bass player at the time, Bryn from the Damned and he invited us to camp with him and so, I camped with him and Rat Scabies and, here I was, this like 22-year-old punk from the United States and all these English people were so fucking cool to me. (36:43:45): Tamara Santibanez What was it like- I mean it sounds like you had an awareness of who they were and you knew their bands. So what was it like to meet these people that youd been listening to, and hearing their music from across an ocean? (36:57:86): Bernie Lieving It was pretty amazing. And I could not believe the graciousness and generosity with which I was welcomed. People- I mean, we left Stonehenge, i guess we were there for, I dont know. Maybe then days? And by the way I got tattooed in a school bus at Stonehenge.',
      605: '(28:57:83): So I, in 82 started playing in a band with Nancy and a couple other friends. One friend Kevin Cher who shot himself in the head about twelve years ago. And couple other, couple other folks and so we played in bands. We played in one band in particular, End of the World where we had an opportunity to open for D.O.A and for GBG and D.R.R and, we actually opened for a band called Hose one time, from New York City and the bass player for hose was Rick Rubin from Def Jam back before Def Jam. And so I think as, once I started listening to all the anarcho punk stuff which was you know, obviously more political and more- I started developing sort of a conscientiousness around animal rights. And being opposed to vivisection. And not wanting to eat animal products anymore and that sort of flowed with the human, I think one of the sayings back then was "animal rights and human liberation are tied to one another.',
      730: '(40:22:78): Bernie Lieving ...But that was a pretty transformative time being in England then and hacing eventually experienced seeing Nancy leaving and going off to Greenham Common. She changed her name to Spider. And so that was a transforamtive experience for her. I also remember panhandling in England and how uncomfortable that me feel to be broke in England. But I was well taken- the British punks just, I mean, I think we have what I was going to say was we we we were invited to a house in Pharom. So I dont know if youve ever heard of the band Polemic. Theyre kind of an obscure anarcho band. Well a couple of members of Polemic lived in Pharom and they invited us to come and they still lived at home with their parents and we got to, we crashed on their floor or couch for a few days. And I guess that was a part of the American punk scene, but mostly if you were like a traveling band. And of course I would say hey, Black Flag, you can crash at my house or whatever. but there was this openness to us and this very generous way of being with us and feeding us and giving us a place to sleep that I had not experienced before in terms of that kind of openess to other peple that was so authentic and kind.',
      805: '(45:02:26): Bernie Lieving ...I was a vegan but I had become increasingly interested in some activism around my politics. And while I was over there that first time there were- I went to a Stop the City March, which is a big thing in Lodon. I went to a number of protests, one, at Porton Down which is a military testing site where they experimented on animals with weapons. And got into like a rock throwing thing with the cops. Can you imagine throwing cops at rocks? I mean throwing rocks at cops? And then throwing them back and not getting shot? I mean that- it was like, this is nuts. Were throwing rocks at each other! We dont live in that world anymore, even in England. But you know, so, went to a bunch of protests and marches. Saw Billy Bragg at Hyde Park for a campaign- at a campaign for a nuclear disarmament rally, went to a anarchist book festival, London and saw Flux of Pink Indians and Chumbawamba and a band called KuKL which was Bjorks band before she was in the Sugar Cubes and before she was Bjork. Well, that was pretty rad and Chumbawamba before they had their hit. (48:25:49): Bernie Lieving So the last few days in London i spent at Fluxs house and they were just so gracious and generous and kind to me. So I left England. I came back to the United States for a while and then I, as I got this sort of activist orientation I went back to England sort of back and to hang out with the people from the southeastern region of the country Southampton, Portsmouth, Bornmouth, Fairham. All those little places sort of in the sort of southeast of Lodon, not too far from London, and I got involved in some Animal Liberation Front activities and ended up breaking into a lab. And getting caught. <Laughs>',
      878: '(27:50:21): Bernie Lieving I think I just sort of having fun with some punk rock buddies and having an adventure. And little did I know what would, you know, obviously unfold ver the next few years as my political, sociopolitical and musical taste would, what path I would, that would follow. What would end up happening with me and- you know, to be in 1981 still eating hamburgers and a couple years later to be a vegan and Ive been a vegan since. And for less, less political now, I mean its still a political aspect of me, but its also just who Ive become. Not so much a statement anymore.',
      910: '(20:30:37): Bernie Lieving Yeah, so... so I barely graduated from high school. I mean I did but barely. And I was-you know, in, so probably in 81, yeah, eighty, late 81 I had got a new girlfriend. Who used heroin. And um, that was new for me. I had used, you know, pot and alcohol and some cocaine. But this was new for me to have someone that I was in a relationship with using heroin. And she, Nancy, had been in the punk scene for quite a while in New York and LA. So she knew Darby Crash. And she knew, she knew all the guys in black Flag. She had hung out at the church in LA. She was she was in kind of the New York sort of scene too. She was in an early move in 79 or 80 where she played a young bartender and so she had a- she sort of took me to the next level, I think in my awareness personally and socially, and I learned a lot from her. Because she was very political already. And it wasnt- you know, during our relationship we became vegans together. Um, in 1983? And in 1984 we went to England together. And she, for lack of a better way of saying it, came out and decided- not decided. But she said Im, I dont want to be in this relationship anymore. Im going to be with women. And she moved to Greenham Common which was the anti-nuclear womens camp there in, I believe, in sort of South Central England. So all that time, the few years that we spent together was very instructive for me in terms of sociopolitiical perspective and my first time sort of having being in love with and being aligned with, not only someone who was using heroin,but someone whose sexual identity seemed to evolve while we were together and that also taught me a lot.',
      1220: '(16:26:15): Bernie Lieving A Plasmatics record, the London Calling came out, of course I was buying, you know, Devo cassetts and so I started transitioning. And by 81 I saw the Ramones for the first time and the last time, I only saw them once. (16:44:40): Tamara Santibanez Oh wow. Can you tell me about- could you remember what that felt like? (16:44:15): Bernie Lieving Oh, it was fucking nuts! I saw them at the Santa Cruz civic auditorium. You probably know Santa Cruz. But that was a pretty big venue and a band, a San Francisco band called the Mutants opened for them and- it was just- you knoe they were like, in 81 the sort of pits were a little different than they got like 82, 84, 85. But there was like circles of movement all throughout the floor of the Santa Cruz Civic. And it smelled of clove cigarettes and, you know, it was- I was sort of taking- I feel like I was learning about my new culture <chuckles> if I think about it in that way. Its like fuck look at- this is like, I mean, I can get the hair standing on the back of my neck thinking about right now because it was so intense. And so ah, powerful and a little overwhelming. The energy was just, unmatched. And the Ramones just fucking killed it. I dont know if you listen to that Ramones live record. It really one of the best live rock records, ever. I think it was recorded in London, but so the. the energy and the vibe and the- not the sound trite, but I felt home. And I think I had been looking for a home for much of my, much of my life. Always sort of- because of always being the new person at a new school. Alway having to live someplace for a year or 2 years or 3 years, or my dads in Vietnam and- so I was always sort of disjointed and never felt a part of much of anything. And I think looking back and sort of talking about this now I think I felt like oh man, I am- this is my thing. And I had the beginnings in 81 of a political consciousness that was, that I can name now, but I wouldnt have been able to name it then, which was, you know anti-racist and and anti-homophobic and anti-misogyny and anti-goverment and- I wouldnt have been able to say that then.',
      1500: '(01:21:33:65): Bernie Lieving You know Ill leave you with this one last thing that I dont think i said, and I sort of made a mental note to say this to you at the begining of our interview when I was thinking about it last night or whatever, is that I purposely sought to mark myself to separate myself from the dominant culture. This was a conscientious act on my part similar to whats on the back of your- the little blurb on the back of your book that I love. That tattooing, not consistently for the last forty-five years, but consistently in general is a big fuck you. And Im not, I dont want to be like you, I dont, I dont accept your strictures, I dont- Im against, you know, your wars, Im against your prison industrial complex, Im against the patriarchy. Even if my neck doesnt say fuck the patriarchy, <laughs> so- I wanted to make sure that I got that in there because that was tied to the early days of being a punk even though I didnt have it formulated then, as I have matured and- and I still feel fuck you! And I still dont want to be a part and, and in some ways, which would be interesting for us to talk about, Im more of a part that Ive ever been. I have my own consulting company. You know, so its- the juxtaposition is very conspicuous. <laughs>'
    },

    4: {
      0: '(18:32:56): Chance Gray: Yeah, yeah, I got arrested a bunch of times in Portland, for relatively minor stuff from like shoplifting and being drunk and so I didnt do any time. Um, but yeah, when I went to LA and I got a case. Less than a year after Ive been there I got a case, and yeah I was locked up for two years. So I was 18, I had just turned 18. So, um, yeah got locked up. LA county jail. State prison. Um, and yeah, ended up doing pretty much exactly two years.',
      40: '(29:33:20): Chance Gray: ...Because jail is just so chaotic and everyones so stressed because theyre fighting their case. Its also like you know, LA County people have neighborhood beefs and all this stuff. Prisons like a little bit more chill. I ended up luckily on a relatively chill, relatively high level but relatively chill, like a lot more like older older dudes who are trying to do their time and stuff.',
      70: '(24:27:20): Chance Gray: Honestly, it was just terrifying. I was like never really... I was always I felt like going under the radar in these like hyper masculine tough environments, you know, and i also went to LA County Jail. This would have been like 2012-2011. And you know all jails are fucked up. Some are worse than others. LA County Jail is like really fucked up. Like its fucking some gestapo shit as soon as you come in. The cops are just screaming at you, throwing stuff at you. Put your chin to your chest. Dont look up, you look up and then they just hit you. You know what I mean?',
      625: '(22:11:51): Chance Gray: The first time I had ever been to a prison, I remember it. I remember everything really well from young childhood and everything. I dont think I was older than six but I went to go visit him in Stockton at YA. And I got really sick and it was like over 100 degrees outside and I had a fever and I was throwing up. And I remember my mom asking the prison if they had any Tylenol or anything to get my fever down. They only had adult Tylenol. And so I remember my mom putting the Tylenol in a banana and tellimg me to chew it. And I remember visiting this guy at YA and I didnt really like understand. I can remember visually all of it and everything but I remember the whole thing about it being really confusing. You know? Like who is he, why is he here, why is everyone dressed the same? All this kind of thing. So I think that experience kind of introduced me to prison, and my mom had a boyfriend who went to prison, actually just got out this year. Twenty years.',
      905: '(43:06:63): Chance Gray: There was a lot of big stuff happening at that time. They called it realignment. So what happened was yeah, it was operating at such high overcrowding - which is funnt like I really have been around the shit for a long time, because like in the 90s when my mom was organzing, it was all about stopping prison construction. And they were successful at that. They stopped prison construction. But the problem was it didnt accompany sentencing reform or anything like that. So they stopped building prisons - but they didnt stop shoving people into prison. So then by then - that was all in the 90s - by like 2012, youre operating at 200% capacity. There was like a lawsuit against the entire California Department of Corrections that made its way to the Federal Supreme Court. The Federal Supreme Court ruled that the entire California prison system was violating cruel and unusual punishment and needed to get like 40,000 people out of the system within six months. So that was like a drastic thing becuase then it was like well where...Are they just gonna let these people go? (44:17:62): Chance Gray And what they did, which was kind of complicated, is they shifted people from State to County Level. Which wasnt necessarily a good thing because... So like I got out of prison. Normally I would have got on parole but because the charge I ended up with was nonviolent, nonsexual I was sent to county probation which meant if I violate probation I go to jail instead of back to prison. So the bad thing was it meant more people were going to the jails because the Supreme Court just said you needed to get people out of the the prison system but didnt say anything about the jails. You know and like I said - jails can be worse and more chaotic. Like prisons are a little more settled. So anyway. Its a really interesting trajectory and then also an an abolitionist and as a political organizer to see how it was a good idea to stop prison construction but like without these other things like actually cause a lot of harm. Like so many people were dying because of overcrowding. And its not their fault. But its you know, I mean its tricky.',
      1030: '(39:06:89): Chance Gray: I dont think I thought about it a lot. Well I dont think i thought about it as much but I think I have definitely been critical of prisons for a long time. And actually one of these alternative cultures that my mom introduced me to was the anti-prison movement. She used to work for this organization called Legal Support for Prisoners with Children. You might have heard of that. Or All of Us or None - which is a project which grew out of Legal Support for Prisoners with Children. So my mom worked for them when I was little and her boss was this woman Ida McCray who was a former political prisoner, Black Radical and did 10 years for allegedly hijacking a plane to Cuba. So I had been introduced to a lot of like anti-prison stuff. I was actually, I was at the founding conference of Critical Resistance as a child. (40:41:11): Chance Gray Yeah and then once I got out later too...When I was in community college, after I got out I went to community college and I started organzing around anti-prison stuff there. Pretty much on my own, just trying to build from nothing basically. And I put together an event and I held a panel and I put that woman on there - Ida McCray - who had been my moms boss when I was a little kid. And then I also ended up rolling with CR - Critical Resistance - for like two or three years. So you know there was always these seeds or whatever. And I think yeah, seeing that guys story - Stan - and how he has just gotten so fucked up from those six years in YA and turned him into a nazi and all these things... I think I was always very critical of prison. And then while I was there I was yeah, now that I think about it, while I was there I was very much like This shit just dont work. I mean even from the perspective of like... I have critiques of things like rehabilitation because its you know, like who gets punished for what and like this kind of thing... but even from a rehabilitative framework, it just wasnt working at all. And this is also at the peak of Californias prison overcrowding crisis. You know, its operating at 200% capacity. So yeah, I think the experience- I dont exactly know how it all ties together. But theres like all these seeds and experiences that have come together into a more coherent politic. Particularly after I got out.',
      1265: '(36:49:94): Chance Gray: I cant remember thinking abut it at the time to be honest, but I do think a lot in general about... as a prison abolitionist Im always interested in... okay, the entire premise of the prison is just the stoppage of everything - emotions, information, care - across a certain boundary. So Im always interested in what makes it across those boundaries and what doesnt and I think tattoos are one of those things. I think mail is super important for that reason. Like mail for the longest time has been... the only thing that crosses that. And then like care and love and emotion as much as they can be through mail or phone or visits - Some people dont have access to any of those things. And like art, you know, Ive collaborated with people on the inside since Ive been out. Ive like tattooed stuff that people on the inside have drawn and Ive done like art exchanges with people.',
      1565: '(45:45:81): Chance Gray: Yeah, lets see. While I was inside I took a history class. I really like that. I always liked history. Even in grade school I took a political science class. And I know at least from those experiences I think I just learned a little bit of discipline around study and stuff like that. It was all self-guided so you kind of had to do that. And then when I got out my plan was not to go to school but I was like well Ill go to community college because you know, I dont know if I can get a job but I can sign up for classes right away. I can get financial aid. Ill do that first semester while I look for a job. I signed up for class like right as a semester was starting in a week or something. So there wasnt very many classes like the Ethnic Studies class, Asian American History. And that was pretty cool, I really liked it. I also started working right away doing restaraunt work. And then Ive done restaraunt work for a long time after that. But yeah I ended up taking that class and then next semester I signed up for more classes and found a history teacher I really like who inspired me to want to become a community college teacher and I just really liked community college. Because my learning experience was so isolated. Also, I was like literally by myself in my cell like writing and reading - that I was really into this communal learning experience. And community college which has formerly incarcerated people and old people and young people and majority working class. It was just a really cool environment and I wanted to do that until I could teach. That was my plan.',
      1670: '(01:15:43:71): Chance Gray: And so I guess two things: One is that like, you know, since this is about imprisonment and tattooing, is like that shit. Like you know Ive been out for 10 years and that experience still has a huge impact and will always have a huge impact on my life. Like theres just more that Im carrying around than a lot of people.',
      1703: '(45:46:81) Chance Gray: So I did really like it there. I got involved in some political organizing and stuff like that and then I transferred to UC Berkeley. And got really deep into the deeper, more academic side of things around like research and I got this really big scholarship to do this research project on prisons and deindustalization and wrote a thesis, graduated like high honors and letters of rec. I have all that planning on going. Taking a year off and going to grad school and then in that year off I changed my mind. <laughs> (48:29:42): Chance Gray: I think that in those- so that was like maybe five or six years of me getting out of prison, in five or six years and in that time I was going to school full time- and really going to school, like straight As yo know, and doing political work and working in restaraunts.'
    },

    5: {
      0: 'Joe Nickley (01:04:00): ...Usually the first few years of drug addiction are pretty romantic and then they just spiral, you know, nobody has enough money and nobody, theres just not enough drugs. I mean, if you sat a propane tank full of heroin behind my house and I could use it every day, I would get boring <laugh>, and Ive also, Ive already done it. Joe Nickley (01:04:57): So Im just like, eh, its cool. I exhausted that technology and thats fine. I took it as far as it would go without, without actually dying.',
      80: 'Joe Nickley (01:00:42): ...These guys were like, it was just another underground thing that I had penetrated. And then that got stupid. It just got boring. I dont know, like, i guess thats that maybe thats the, the, the pathos, you know what I mean? They always lose their steam after a little bit, you know what I mean? Right. And then youre with it, you know, like, you know, you cant just like step off heroin. But yeah, tattooing got that way. And so at one point, well, I got fired for drug use, and then I worked at a couple of shops and I was just like, man, I just dont even want to tattoo anymore.',
      125: 'Joe Nickley (00:21:54): My things in life was like, Im either going to be a professional skateboarder, which, I skateboard— everything I do in life, I do— I mean, compulsive is one way, alcoholically is another way. My body was shot by the time I was 17, 18 years old from skateboarding. I was, it was— literally every trick was the end of the world to me. So I either was gonna be a pro at skateboarding and make a living until my body gave out, or tattooing seemed to be a little bit more were sustainable. Joe Nickley (00:22:51): Plus it was my first love. I played music and I skated and stuff like that, and Dana was just like, you cant serve two masters, you know what I mean? Its like skateboarding— the problem with that was I was always breaking my hand skateboarding and always, I was very quick to punch anybody who got in my way about— skateboarding. You know, I just had got to that point with with rednecks and cops and any kind of policious behavior from another human. I was very— I just got tired of getting beat on about it. And so I just <laugh>, if I couldnt get respect, fear was enough at that point.',
      160: 'Joe Nickley (00:58:24): And that was me, I think, searching for another underworld. Tattooing was starting to get popular. And I was really almost offended by that. I had almost black hands by the time I was 23, 24 and my neck tattooed, head tattoos. I definitely crossed those weird lines. That being said, it started to not be a big deal and that, I dont know, you know what I mean? I just thought it was a strange thing. And so I just started, I got into heroin and heroin was really awesome. Underworld. That was a hard one, you know, and Im not romanticizing heroin. Its, its, its not a sustainable technology <laugh> but it really had a, a, again, it was an a, I dont know, I dont know how to describe it.',
      254: 'Joe Nickley (00:59:30): Uh, <laugh> dangerous. I guess that was it. Tattooing, the danger was gone, you know what I mean? Thats part of the excitement, especially as a young person. The dangerous situation stepping into the, the meth house and getting tattooed, or get, I remember leaving the tattoo and driving home and just being like, I am unlike other people, you know what I mean? I was fortifying that. I was really taking this stance. Im an outlaw kind of thing.',
      350: 'Joe Nickley (01:04:00): And Im like, Im just— doing something. I dont know. You know what I mean? So I think that there was that thing in there where it was kind of pushing me to be more expressive and a, to develop my own sound. But I also was, I was busy chasing drugs and trying to sustain a lifestyle, and just sustain life at that point, you know. Life had gotten pretty wild at that point. Usually the first few years of drug addiction are pretty romantic and then they just spiral, you know, nobody has enough money and nobody, theres just not enough drugs. I mean, if you sat a propane tank full of heroin behind my house and I could use it every day, I would get boring <laugh>, and Ive also, Ive already done it. Joe Nickley (01:04:57): So Im just like, eh, its cool. I exhausted that technology and thats fine. I took it as far as it would go without, without actually dying. But I did, there was a lot of stuff to come from it, I was a punk kid. So I wouldnt listen to anything but that, and then I started, you know, getting high and I was like, oh, jazz is good. You know, <laugh> <laugh> wow, this is good. Thats good. This is really good. Its a vampire drug though. Its like first comes the rose, then the thorn, you know. <laugh>',
      500: 'Joe Nickley (01:05:52): Any person thats ever gone to prison, there is a drug or alcohol aspect of it. Which usually if you go all the way back that goes to a class aspect of it, but Im just gonna say yes, heroin had a lot to do with it, but it was also kind of one of my saving graces also. So, I had gotten sober a few times, but the company I kept at the time, you know, its like, when in Rome, right? If you hang around with maniacs, youre going to do maniac shit, whether youre sober or drunk, but it really helps to not be sober. So most crimes have an element of drug addiction or alcohol addiction or, you know, just things going too far because of it, of the fuel of it.',
      620: 'Joe Nickley (01:06:52): But yeah, Ive been sober a few times and then the, my crime was eight years old <affirmative> when I got arrested for it. And I had literally, I had hit that spot where there was no— there was nowhere else to go. I had run out of, I had run out of runs. And it was really funny, it was the night before I remember, I had not got my teeth knocked out when I was younger in a fight. Some dude bricked me in the face. So all my top teeth were gone and they were hurting so bad. You know, I said like hacked teeth up in my head, you know? And I tattooed dope sick for like 10 hours. And then I finally got the dope and I got high and it didnt really do anything.',
      785: 'Joe Nickley (01:07:41): I dont know. It was just weird. And I had that, what addicts will refer to as that moment of clarity, which you had multiples of those, but this one was crazy. And I remember just crying and sitting down and being like, what happened to me? You know what I mean? Like what happened? Like Ive always been so sovereign, now Im, my life is dictated by a drug dealer. I thought that was so weird. I was like, I just gave it away, man. Its like, I was, I hate using that word, but, and I use that with, with, with pliers, you know, punk, but like I did shit exactly as I wanted to do it at, at, at whatever cost, you know what I mean? Its like, I did what I was inclined to do at the time. Joe Nickley (01:08:32): So having a master like that just totally disengaged all sovereignty that I thought I had. And it wasnt a mental thing, you know, I was physically addicted. So it was like, within eight hours I was going to be sick and I was gonna make horrible decisions, you know? It sucked. I also was probably the most disciplined junkie ever in the world. I only got high at 8:00 AM and 8:00 PM. <laugh> <laugh>',
      818: 'Joe Nickley (01:12:29): And it just wasn’t happening. And I was like all right. I know Im a liar. I know Im not gonna sustain it. And I remember getting on my hands and knees and being like father save your servant, and make it so bad that I lose the taste for this. And it was funny years later, I was watching a movie thats the first line of an exorcism. And, uh, it was crazy. It was like 14 days. People are like, oh man, I drank ayahuasca, and this happened, I was like, let me tell you about my drug kick. And they were just like, wow. You know, I dont <laugh>, I dont recommend it, <laughs> but it was the lesson I had to, I had to go through <affirmative> and then I got to, I got to county jails and county jail for 13 and a half months and, fighting this case and getting sober.',
      915: 'Joe Nickley (01:13:30): And then I was like, you have a lot of time to, to think about how did you get there?',
      955: 'Joe Nickley (01:15:21): So yeah, so in county jail, I really kind of got my chops together. Those things started like, like I did a tattoo on myself, in county jail, with a sharpened staple. Melted it on a toothbrush and I just tattooed “adapt” and “endure” on my wrist. And so I was like back to being a kid putting mantras on myself. I mean, they look like shit, but I wouldnt cover em, you know, theyre just like, man, I can, I look at em and Im right there. You know, its like, the tattoo is a consequence of an experience, you know what I mean? So you see, you, its the story thats in those lines, you know what I mean? Joe Nickley (01:16:14): So when I look at em like, whenever Im feeling lack of gratitude about something, I look at those tattoos and Im just like, man, I could be in county jail with nothing. But I had my body, you know what I mean? And so I got really into working out, but you know, I was just like, man, like trying to find my voice at that time period. You know what I mean? And then I, due to lack of evidence, I got a very, very low number.',
      970: 'Joe Nickley (01:21:41): You know, if you sit around on the phone all day with the outside world, youre in for a load of suffering because youre not in that world and you cant, you don’t have any control over it, you know? So its like immerse yourself in prison and then go home and do your best to like adapt back to, the world, which the world changes so much. You know, even in three, four years, you know, you go home and its just a different world, you know, the way people talk to each other.',
      1000: 'Keywords: Easy Rider, carnival, side show, skateboard, skating, the Germs, punk, Shadow, Spider Sinclair, the Pike, Carlos Truan, Designs by Dana, Dana Brunson, Dot Brunson, Andrew Hoctor, Greg Cole, Chet Cain, Paul Rogers, Spaulding and Rogers, Robert Benedetti, Sunset Strip Tattoo, Tennessee Dave, Nick Bubash, Thom Devita, Mike McCabe, Leo Zulueta, Old Soul, Jeff Zuck, Fakir Musafar, Ohio, rural, motorcycles, outlaw, bikers, piercing, modern primitives, black and grey, panther, Sun Ra, Howard Fenster, jazz, Eddie Owens Martin, military, Americanized Japanese, magic, Maori, New Zealand, Bill Renick, gay, S&M, heroin, drug use, straight edge, single needle, county jail, prison, Black Flag, Greg Ginn, prison tattoo, Marvin Renter, art, Ed Hardy, Bloods, Crips, Aryans, yoga, Heartless Felons, art, painting'
    }

  }

  var wrapper = $('#wrapper')[0]
  document.addEventListener('scroll', function (event) {
    if (event.target.id == 'wrapper') {
      var point = wrapper.scrollTop
      console.log({point})
      // console.log(point.split(','));
      var message = messages[n][point]
      if (message) {
        $('.transcript-container').text(message)
      }
    }
  }, true)

})
